defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      image: ""


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CNAME
  - LICENSE
  - README.md
  - webpack.config.js
  - "*.lock"
  - "*.log"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# meta tags
title: Digifair Note
email: hi@digifair.com
description: Digifair Note is a fabric sourcing and inspiration productivity app for fashion buyers and fashion designers. Upload photos of fabrics, register your suppliers' contacts, track fabric trade shows - all in one single app.
permalink: /:slug/
# url
url: "https://site-one-theta.now.sh"
# url: "https://www.digifair.com/"

# Google Analytics
google_analytics: UA-166133551-1
# Google Tag Manaager
google_tag_manager: GTM-K83C7ZM
