collections:
  authors:
    output: true

defaults:
  -
   values:
      sitemap: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CNAME
  - LICENSE
  - README.md
  - webpack.config.js
  - "*.lock"
  - "*.log"



title: Digifair Note
email: hi@digifair.com
description: Digifair Note is a fabric sourcing and inspiration productivity app for fashion buyers and fashion designers. Upload photos of fabrics, register your suppliers' contacts, track fabric trade shows - all in one single app.
baseurl: ""
logo: "assets/images/logo.png"
url: "https://www.textilerequests.com"
