defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
      image: /assets/images/default-card.png


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - CNAME
  - LICENSE
  - README.md
  - webpack.config.js
  - "*.lock"
  - "*.log"


# meta tags
title: Digifair Note
email: hi@digifair.com
description: Digifair Note is a fabric sourcing and inspiration productivity app for fashion buyers and fashion designers. Upload photos of fabrics, register your suppliers' contacts, track fabric trade shows - all in one single app.
permalink: /:slug/
# url
baseurl: ""
url: "https://www.textilerequests.com"
# Google Analytics
google_analytics: UA-166133551-1
