- url: 'https://fabricsight.com/products/european-certified-linen-120-melange/?utm_source=digifairnote&amp;utm_medium=lp&amp;utm_campaign=carrossel'
  image: 'https://digifair.com/wp-content/uploads/2020/01/ESE-LI-120-310-SG-SEMIGREY-Fabric-Sight-00_1024x1024@2x.jpg'
  name: European Certified Linen, natural color
- url: 'https://fabricsight.com/products/light-brush-recycled-wool/?utm_source=digifairnote&amp;utm_medium=lp&amp;utm_campaign=carrossel'
  image: 'https://digifair.com/wp-content/uploads/2020/01/RUT_2303_green_pink_Fabric-Sight-00_1024x1024@2x.jpg'
  name: Light Brush Recycled Wool
- url: 'https://fabricsight.com/products/Wool-Blend-Twill-Blue/?utm_source=digifairnote&amp;utm_medium=lp&amp;utm_campaign=carrossel'
  image: 'https://digifair.com/wp-content/uploads/2020/01/RUT_401_BLUE-FabricSight-00_1024x1024@2x-1.jpg'
  name: Wool Blend Twill
- url: 'https://fabricsight.com/products/super-soft-cupro-blend-twill-vegan-certified-amber/?utm_source=digifairnote&amp;utm_medium=lp&amp;utm_campaign=carrossel'
  image: 'https://digifair.com/wp-content/uploads/2020/01/IPE-AQUA-00700-ORANGE-Fabric-Sight-00_1024x1024@2x.jpg'
  name: Super Soft Cupro Blend Twill, Vegan Certified
- url: 'https://fabricsight.com/products/cupro-viscose-satin-100-vegan-certified-fire-red/?utm_source=digifairnote&amp;utm_medium=lp&amp;utm_campaign=carrossel'
  image: 'https://digifair.com/wp-content/uploads/2020/01/IPE_00558_AMARA_11737-FabricSight-01_1024x1024@2x.jpg'
  name: Cupro Viscose Satin, 100% Vegan Certified
